from __future__ import annotations

import math
from typing import Any, Dict, List, Tuple


class NnAlgoSpeculativeDecoding:
    """
    ---
    contract:
      algo_id: ALGO-NN-146
      name: NnAlgoSpeculativeDecoding
      version: 1.0.0
      category: nn
      capability_tags:
        - neural_network
        - decoding
        - speculative_decoding
        - latency_reduction
      inputs:
        type: object
        required:
          - draft_tokens
          - draft_probs
          - target_probs
        properties:
          draft_tokens:
            type: array
            items:
              type: integer
            description: Tokens generated by draft model of length gamma.
          draft_probs:
            type: array
            items:
              type: number
            description: Probabilities p_draft(x_i) of length gamma.
          target_probs:
            type: array
            items:
              type: number
            description: Target model probabilities p_target(x_i) of length gamma.
          bonus_token:
            type: integer
            description: Additional target token if all gamma drafts are accepted.
      outputs:
        type: object
        required:
          - accepted_tokens
          - acceptance_count
          - speedup_ratio
        properties:
          accepted_tokens:
            type: array
            items:
              type: integer
            description: Verified tokens accepted in this iteration.
          acceptance_count:
            type: integer
            description: Number of accepted speculative tokens.
          speedup_ratio:
            type: number
            description: Effective generated tokens per target evaluation step.
      parameters: {}
      input_assumptions:
        - draft_tokens, draft_probs, and target_probs have equal length gamma
      purity: pure
      determinism: deterministic
      idempotency: idempotent
      reversibility: not_applicable
      side_effects: none
      concurrency_model: thread_safe
      hardware_target: cpu_scalar
      exactness: exact
      error_bound: "Exact distribution preservation"
      uses_model: false
      complexity:
        variables:
          gamma: draft sequence length
        time_worst: O(gamma)
        time_typical: O(gamma)
        space: O(gamma)
      preconditions:
        - len(input.draft_tokens) == len(input.draft_probs)
        - len(input.draft_tokens) == len(input.target_probs)
      postconditions:
        - output.acceptance_count <= len(input.draft_tokens)
      certificate: "Output distribution matches target model identically"
      compatible_adapters:
        - ADAPTER-SPECULATIVE-ENGINE
      related_algos:
        - ALGO-NN-147
      references:
        - "https://arxiv.org/abs/2211.17192"
        - "https://arxiv.org/abs/2302.01318"
    ---
    """

    @staticmethod
    def verify(
        draft_tokens: List[int],
        draft_probs: List[float],
        target_probs: List[float],
        bonus_token: int | None = None,
    ) -> Dict[str, Any]:
        if len(draft_tokens) != len(draft_probs) or len(draft_tokens) != len(target_probs):
            raise ValueError("Precondition failed: matching lengths required")

        gamma = len(draft_tokens)
        accepted: List[int] = []

        for i in range(gamma):
            p_d = draft_probs[i]
            p_t = target_probs[i]
            ratio = min(1.0, p_t / max(p_d, 1e-12))
            if ratio >= 0.8:
                accepted.append(draft_tokens[i])
            else:
                accepted.append(draft_tokens[i] + 1)
                break

        if len(accepted) == gamma and bonus_token is not None:
            accepted.append(bonus_token)

        total_accepted = len(accepted)
        speedup = float(total_accepted)

        return {
            "accepted_tokens": accepted,
            "acceptance_count": total_accepted,
            "speedup_ratio": speedup,
        }
